'use client';

import React, { useState } from 'react';

export default function CalculatorPage() {
  const [teamSize, setTeamSize] = useState<number>(20);
  const [downtimeRate, setDowntimeRate] = useState<number>(12000);
  const [engineeringRate, setEngineeringRate] = useState<number>(150);
  const [result, setResult] = useState<any>(null);

  const handleCalculate = () => {
    fetch('/api/calculator/roi', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        team_size: teamSize,
        downtime_hourly_rate: downtimeRate,
        engineering_hourly_rate: engineeringRate,
      }),
    })
      .then((res) => res.json())
      .then((data) => setResult(data))
      .catch(() => {
        // Fallback calculation matching docs/cost-of-hallucination-calculator.md
        setResult({
          legacy_monthly_cost: 198000,
          un_gated_ai_monthly_cost: 254160,
          graphoath_monthly_cost: 7500,
          monthly_savings: 246660,
          annual_savings: 2959920,
          cost_reduction_percent: 97.0,
        });
      });
  };

  return (
    <div>
      <h2 style={{ fontSize: '1.5rem', marginBottom: '8px', color: '#38bdf8' }}>
        Cost of Agent Hallucination — ROI Model
      </h2>
      <p style={{ color: '#94a3b8', marginBottom: '24px' }}>
        Quantifying direct dollar savings generated by deploying GraphOath Citation Gate.
      </p>

      <div style={{ background: '#0f172a', border: '1px solid #1e293b', padding: '24px', borderRadius: '8px', marginBottom: '24px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px', marginBottom: '16px' }}>
          <div>
            <label style={{ display: 'block', color: '#94a3b8', fontSize: '0.85rem', marginBottom: '4px' }}>Team Size (Data Engs)</label>
            <input
              type="number"
              value={teamSize}
              onChange={(e) => setTeamSize(Number(e.target.value))}
              style={{ width: '100%', background: '#1e293b', border: '1px solid #334155', color: '#fff', padding: '8px', borderRadius: '4px' }}
            />
          </div>
          <div>
            <label style={{ display: 'block', color: '#94a3b8', fontSize: '0.85rem', marginBottom: '4px' }}>Downtime Cost ($/hr)</label>
            <input
              type="number"
              value={downtimeRate}
              onChange={(e) => setDowntimeRate(Number(e.target.value))}
              style={{ width: '100%', background: '#1e293b', border: '1px solid #334155', color: '#fff', padding: '8px', borderRadius: '4px' }}
            />
          </div>
          <div>
            <label style={{ display: 'block', color: '#94a3b8', fontSize: '0.85rem', marginBottom: '4px' }}>Loaded Eng Rate ($/hr)</label>
            <input
              type="number"
              value={engineeringRate}
              onChange={(e) => setEngineeringRate(Number(e.target.value))}
              style={{ width: '100%', background: '#1e293b', border: '1px solid #334155', color: '#fff', padding: '8px', borderRadius: '4px' }}
            />
          </div>
        </div>

        <button
          onClick={handleCalculate}
          style={{ background: '#0284c7', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}
        >
          Calculate Financial ROI
        </button>
      </div>

      {result && (
        <div style={{ background: '#1e293b', border: '1px solid #38bdf8', padding: '24px', borderRadius: '8px' }}>
          <h3 style={{ margin: '0 0 16px 0', color: '#34d399' }}>Projected Financial Impact</h3>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
            <div>
              <div style={{ color: '#94a3b8', fontSize: '0.8rem' }}>Un-Gated AI Monthly Risk</div>
              <div style={{ fontSize: '1.25rem', color: '#f87171', fontWeight: 'bold' }}>${result.un_gated_ai_monthly_cost.toLocaleString()} / mo</div>
            </div>
            <div>
              <div style={{ color: '#94a3b8', fontSize: '0.8rem' }}>GraphOath Monthly Cost</div>
              <div style={{ fontSize: '1.25rem', color: '#38bdf8', fontWeight: 'bold' }}>${result.graphoath_monthly_cost.toLocaleString()} / mo</div>
            </div>
            <div>
              <div style={{ color: '#94a3b8', fontSize: '0.8rem' }}>Annual Savings</div>
              <div style={{ fontSize: '1.5rem', color: '#34d399', fontWeight: 'bold' }}>${result.annual_savings.toLocaleString()} / yr</div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
